package com.abbink.simplewebstack.webapp.di;

import static com.abbink.simplewebstack.common.data.di.DataModule.JDBC_URL;
import static com.abbink.simplewebstack.common.data.di.DataModule.SQL_DIALECT;
import static com.abbink.simplewebstack.common.auth.shiro.di.AuthShiroModule.SHIRO_REMEMBERME_KEY;

import com.google.inject.AbstractModule;
import com.google.inject.Key;
import com.google.inject.name.Names;

public class ConfigModule extends AbstractModule {
	
	@Override
	protected void configure() {
		bind(Key.get(String.class, Names.named(JDBC_URL))).toInstance("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1");
		bind(Key.get(String.class, Names.named(SQL_DIALECT))).toInstance("H2");
		
		// generated by {@link AesCipherService#generateNewKey()} with a 256b key size
		bind(Key.get(String.class, Names.named(SHIRO_REMEMBERME_KEY))).toInstance("SVAJMiJLY+u3mrLTWF66MPz/cfXguAHqXwJhvomkfXc=");
	}
	
}
